name: High Impact Alert

on:
  pull_request:
    types:
      - labeled

env:
  MILO_COMMUNITY_SLACK_WEBHOOK: ${{ secrets.MILO_COMMUNITY_SLACK_WEBHOOK }}

jobs:
  send_alert:
    if: github.repository_owner == 'overmyheadandbody'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - name: Send Slack message for high impact PRs
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const main = require('./.github/workflows/high-impact-alert.js')
            main({ github, context })
